Submit dependabot dependency graph to Github
apache/incubator-pekko-management pull request #93
Opened 2023-06-06 19:11 UTC by mdedetrich

This PR uses scala centers official integration of sbt with github's dependabot (see https://github.com/scalacenter/sbt-dependency-submission) to submit any potential security vulnerabilities. This is a more practical solution compared to https://github.com/apache/incubator-pekko/pull/289 especially in regards to getting it ready for release candidate.

2023-06-07 02:50 UTC, He-Pin requested changes
file name is wrong

2023-06-07 02:50 UTC, He-Pin commented on .github/workflows/depedency-graph.yml
> +name: Update Dependency Graph
dependency-graph.yml

2023-06-07 08:37 UTC, mdedetrich commented on .github/workflows/depedency-graph.yml
> +name: Update Dependency Graph
Fixed.

2023-06-08 10:22 UTC, mdedetrich commented
@He-Pin This is fixed now

2023-06-08 13:16 UTC, merged